# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger: none
pr: none

pool: sonicbld

variables:
  TIMEOUTINMINUTES: 1

stages:
- stage: Build
  jobs:
  - template: .azure-pipelines/azure-pipelines-job-groups.yml
    parameters:
      preSteps:
      - script: |
          echo preStep
        displayName: preStep
      postSteps:
      - script: |
          echo postStep
        displayName: postStep
      jobGroups:
      - name: vs
        script: |
          echo vs
      - name: broadcom
        script: |
          echo broadcom
      - name: barefoot
        script: |
          echo barefoot
