# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: sonicbld
jobs:
- job: Job1
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      echo sleep 300 seconds
      echo test
      sleep 300
    displayName: 'Run a multi-line script'
- job: Job2
  steps:
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      exit 1
    displayName: 'Run a multi-line script'
