# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 8 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true
 
trigger: none
pr: none

parameters:
  - name: TEST
    type: string
    default: $(platform)

jobs:
- template: .azure-pipelines/build-template.yml
  parameters:
    platform: ${{ parameters.TEST }}
    platform_short: ${{ parameters.TEST }}
    cache_mode: wcache
    swi_image: true