# partition related config

## Partition size in MB
ONIE_IMAGE_PART_SIZE=2048

## Output file name for compressed file system
DEMO_SYSROOT_IMAGE_GZ=fs.img.gz
OUTPUT_ONIE_IMAGE=acs.bin

TARGET_PLATFORM=x86_64
TARGET_MACHINE=generic
ONIEIMAGE_VERSION=r0
DEMO_SYSROOT_IMAGE_GZ=fs.img.gz
OUTPUT_ONIE_IMAGE=acs-$TARGET_MACHINE.bin
