# Publish the SONiC release notes to PhynetTSG

schedules:
- cron: "0 8 * * *"
  displayName: Daily build
  branches:
    include:
    - internal
  always: false
trigger: none
pr: none
resources:
  repositories:
  - repository: PhynetTSG
    type: git
    name: PhyNet/PhynetTSG
    ref: PhynetTSG

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'ubuntu-20.04'

parameters:
- name: 'tags'
  type: object
  default: []

variables:
  DEFAULT_BRANCH_REGEX: "internal-202[2-9][0-9][0-9]"
  DEFAULT_TAG_REGEX: '202[2-9][0-9]{3}\.[0-9]{1,3}'
  PHYNET_URL_PREFIX: "https://dev.azure.com/msazure/PhyNet/_apis/git/repositories/PhynetTSG/pullrequests"

stages:
- stage: Build
  jobs:
  - job: Publish
    steps:
    - checkout: self
      fetchTags: true
      persistCredentials: true
    - checkout: PhynetTSG
      persistCredentials: true
    - task: ADXQuery@1
      inputs:
        targetType: 'inline'
        script: |
          print A="Hello";
          print B="Hello";
        kustoUrls: 'https://sonic.westus2.kusto.windows.net:443?DatabaseName=internal'
        customAuth: true
        connectedServiceName: 'SONiCDataExplorer'
        minThreshold: '0'
        maxThreshold: '100'
        OutputFile: 'release_notes.json'
    - script: |
        ls -lt
        SOURCE_BRANCH=sonic/release-notes-t1
        TARGET_BRANCH=sonic/release-notes-main
        TAG=20220531.11
        TITLE="Add SONiC release note $TAG"
        DESCRIPTION=$TITLE
        BODY='{"sourceRefName": "refs/heads/'$SOURCE_BRANCH'", "targetRefName": "refs/heads/'$TARGET_BRANCH'", "title": "'$TITLE'", "description": "'$DESCRIPTION'"}'
        git config --global user.email "sonicbld@microsoft.com"
        git config --global user.name "Sonic Build Admin"
        cat release_notes.json
        cd PhynetTSG
        git checkout -b $SOURCE_BRANCH origin/$TARGET_BRANCH
        echo $RANDOM > test
        git add test
        git commit -m "test"
        git push --set-upstream origin $SOURCE_BRANCH  -f
        curl -X POST -L -H 'Content-Type: application/json' -H 'Accept: application/json' -u :$(System.AccessToken) \
        "$PHYNET_URL_PREFIX?api-version=5.1" \
        -d "$BODY"
      displayName: "List files"
