# Publish the SONiC release notes to PhynetTSG

schedules:
- cron: "0 8 * * *"
  displayName: Daily build
  branches:
    include:
    - internal
  always: false
trigger: none
pr: none
resources:
  repositories:
  - repository: PhynetTSG
    type: git
    name: PhyNet/PhynetTSG
    ref: PhynetTSG

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'ubuntu-20.04'

parameters:
- name: 'tags'
  type: object
  default: []

variables:
  DEFAULT_BRANCH_REGEX: "^refs/remotes/origin/internal-(202205|2023[0-9][0-9]|20[3-9][0-9][0-9][0-9])$"
  DEFAULT_TAG_REGEX: '^refs/tags/20[0-9]{6}\.[0-9]{1,3}$'
  PHYNET_URL_PREFIX: "https://dev.azure.com/msazure/PhyNet/_apis/git/repositories/PhynetTSG/pullrequests"

stages:
- stage: Build
  jobs:
  - job: Publish
    steps:
    - checkout: self
      fetchTags: true
      persistCredentials: true
    - checkout: PhynetTSG
      persistCredentials: true
    - script: |
        cd PhynetTSG/wiki/sonic/release-notes
        releasenotes=$(ls 202*/*.md | grep -iE '^[0-9]+/SONiC\.[0-9]{8}\.[0-9]{1,3}\.md')
        echo "$releasenotes"
        maxReleaseVersions=$(echo "$releasenotes" | cut -d. -f2,3 | sort -n -t. -r -k1,1 -k2 | sort -n -r -t. -k1,1 -u)
        echo "The maximum release versions:"
        echo "$maxReleaseVersions"
        echo "##vso[task.setvariable variable=MAX_RELEASE_VERSIONS]$maxReleaseVersions"
      displayName: "Set variables"
    - task: ADXQuery@1
      inputs:
        targetType: 'inline'
        script: |
          print A="Hello";
          print B="Hello";
        kustoUrls: 'https://sonic.westus2.kusto.windows.net:443?DatabaseName=internal'
        customAuth: true
        connectedServiceName: 'SONiCDataExplorer'
        minThreshold: '0'
        maxThreshold: '100'
        OutputFile: 'release_notes.json'
    - script: |
        ls -lt
        echo "MAX_RELEASE_VERSION=$MAX_RELEASE_VERSIONS"
        sudo apt update
        sudo apt install -y jq
        SOURCE_BRANCH=sonic/release-notes-t1
        TARGET_BRANCH=sonic/release-notes-main
        # See https://dev.azure.com/msazure/One/_apis/git/repositories/Networking-acs-buildimage/pullrequests/9296449/reviewers?api-version=7.1
        REVIEWER_ID=1b5f2f1b-141f-65e4-b96d-29a1a9a73edd
        TAG=20220531.11
        TITLE="Add SONiC release note $TAG"
        DESCRIPTION=$TITLE
        BODY='{"sourceRefName": "refs/heads/'$SOURCE_BRANCH'", "targetRefName": "refs/heads/'$TARGET_BRANCH'", "title": "'$TITLE'", "description": "'$DESCRIPTION'"}'
        git config --global user.email "sonicbld@microsoft.com"
        git config --global user.name "Sonic Build Admin"
        cat release_notes.json
        cd PhynetTSG
        git checkout -b $SOURCE_BRANCH origin/$TARGET_BRANCH
        echo $RANDOM > test
        git add test
        git commit -m "test"
        # Force Push
        git push --set-upstream origin $SOURCE_BRANCH  -f
        # Submit the PR
        curl -X POST -L -H 'Content-Type: application/json' -H 'Accept: application/json' -u :$(System.AccessToken) "$PHYNET_URL_PREFIX?api-version=7.0" -d "$BODY"
        # Query the PR
        PRID=$(curl -L -H 'Content-Type: application/json' -H 'Accept: application/json' -u :$(System.AccessToken) "$PHYNET_URL_PREFIX?api-version=7.0&searchCriteria.sourceRefName=refs/heads/$SOURCE_BRANCH" | jq '.value[0].pullRequestId')
        if [ -z "$PRID" ]; then
            echo "Failed to query the PR" 1>&2
            exit 1
        fi
        # sonicbld will approve the PR for PR complete automation
        curl -X PUT -L -H 'Content-Type: application/json' -H 'Accept: application/json' -u :$(MSAZURE_PAT) "$PHYNET_URL_PREFIX/$PRID/reviewers/$REVIEWER_ID?api-version=7.0" -d '{"vote":10}'
        # Print the PR link
        echo "Pull Request: https://dev.azure.com/msazure/PhyNet/_git/PhynetTSG/pullrequest/$PRID"
      displayName: "List files"
