# Publish the SONiC release notes to PhynetTSG

schedules:
- cron: "0 8 * * *"
  displayName: Daily build
  branches:
    include:
    - internal
  always: false
trigger: none
pr: none
resources:
  repositories:
  - repository: PhynetTSG
    type: git
    name: PhyNet/PhynetTSG
    ref: PhynetTSG

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'ubuntu-20.04'

variables:
  PHYNET_URL_PREFIX: "https://dev.azure.com/msazure/PhyNet/_apis/git/repositories/PhynetTSG/pullrequests"
  SOURCE_BRANCH: sonic/firmware-profile-t1
  TARGET_BRANCH: sonic/firmware-profile-main

stages:
- stage: Build
  jobs:
  - job: Publish
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'
    - checkout: self
      fetchTags: true
    - checkout: PhynetTSG
      persistCredentials: true
    - script: |
        sudo apt update
        sudo apt install -y jq python3
        sudo pip3 install j2cli
      displayName: "Install tools"
    - task: ADXQuery@1
      inputs:
        targetType: 'inline'
        script: |
          GetFirmwareProfileReleaseNotes()
        kustoUrls: 'https://sonic.westus2.kusto.windows.net:443?DatabaseName=internal'
        customAuth: true
        connectedServiceName: 'SONiCDataExplorer'
        minThreshold: '0'
        maxThreshold: '100'
        OutputFile: 'firmware_profile.json'
    - script: |
        ls -lt
        # See https://dev.azure.com/msazure/One/_apis/git/repositories/Networking-acs-buildimage/pullrequests/9296449/reviewers?api-version=7.1
        REVIEWER_ID=1b5f2f1b-141f-65e4-b96d-29a1a9a73edd
        TITLE="Update SONiC Firmware Profile doc"
        DESCRIPTION=$TITLE
        BODY='{"sourceRefName": "refs/heads/'$SOURCE_BRANCH'", "targetRefName": "refs/heads/'$TARGET_BRANCH'", "title": "'$TITLE'", "description": "'$DESCRIPTION'"}'
        export UPDATE_TIMESTAMPE=$(cat ../firmware_profile.json | jq -r '.body.Tables[0].Rows[0][1]')
        export FIRMWARE_PROFILE_VERSIONS=$(cat ../firmware_profile.json | jq -r '.body.Tables[0].Rows[0][0]')
        j2 Networking-acs-buildimage/.pipelines/templates/firmware-profile-versions.md.j2 > PhynetTSG/wiki/sonic/release-notes/firmware-profile-versions.md
        cd PhynetTSG
        git checkout -b $SOURCE_BRANCH origin/$TARGET_BRANCH
        git config --global user.email "sonicbld@microsoft.com"
        git config --global user.name "Sonic Build Admin"
        cd PhynetTSG
        git status
        git add '*.md'
        git status
        git commit -m "$TITLE"
        # Force Push
        git push --set-upstream origin $SOURCE_BRANCH  -f
        # Submit the PR
        curl -X POST -L -H 'Content-Type: application/json' -H 'Accept: application/json' -u :$(System.AccessToken) "$PHYNET_URL_PREFIX?api-version=7.0" -d "$BODY"
        # Query the PR
        PRID=$(curl -L -H 'Content-Type: application/json' -H 'Accept: application/json' -u :$(System.AccessToken) "$PHYNET_URL_PREFIX?api-version=7.0&searchCriteria.sourceRefName=refs/heads/$SOURCE_BRANCH" | jq '.value[0].pullRequestId')
        if [ -z "$PRID" ]; then
            echo "Failed to query the PR" 1>&2
            exit 1
        fi
        # sonicbld will approve the PR for PR complete automation
        curl -X PUT -L -H 'Content-Type: application/json' -H 'Accept: application/json' -u :$(MSAZURE_PAT) "$PHYNET_URL_PREFIX/$PRID/reviewers/$REVIEWER_ID?api-version=7.0" -d '{"vote":10}'
        # Print the PR link
        echo "Pull Request: https://dev.azure.com/msazure/PhyNet/_git/PhynetTSG/pullrequest/$PRID"
      displayName: "Send or update Pull Request"
