# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

schedules:
- cron: "0 0 * * 0"
  displayName: Weekly Build
  branches:
    include:
    - xumia/*

pool: sonicbld

stages:
- stage: Build
  jobs:
  - template: azure-pipelines-build.yml
    parameters:
      buildSlave: y
- stage: UpgradeVersions
  jobs:
  - job: UpgradeVersions
    steps:
    - script: |
        sudo rm -rf *
      displayName: 'cleanup'
    - checkout: self
      displayName: 'Checkout code'
    - download: current
      patterns: '**/versions-*'
    - script: |
        mkdir -p target
        default_platform=broadcom
        artifacts=$(find $(Pipeline.Workspace) -maxdepth 1 -type d -name 'sonic-buildimage.*' | grep -v "sonic-buildimage.${default_platform}")
        echo "artifacts$artifacts"
        cp -r $(Pipeline.Workspace)/sonic-buildimage.${default_platform}/versions target/
        make freeze FREEZE_VERSION_OPTIONS=-r
        find files/build/versions 
        for artifact in $artifacts
        do
          rm -rf target/versions
          cp -r $artifact/versions target/
          make freeze FREEZE_VERSION_OPTIONS="-a -d"
        done
        git diff files/build/versions
      displayName: "Freeze Versions"
    - publish: $(System.DefaultWorkingDirectory)/files/build/versions
      artifact: 'sonic-buildimage.versions'
      displayName: "Archive sonic versions"
    
