parameters:
- name: connectionName
  type: string
  default: sonic-dev-connection
- name: kevaultName
  type: string
  default: sonic-kv
- name: certificateName
  type: string
  default: sonic-secure-boot
- name: privateKeyPath
  type: string
  default: /etc/certificates/sonic-secure-boot-private.pem
- name: certificatePath
  type: string
  default: /etc/certificates/sonic-secure-boot-public.pem

steps:
- task: AzureKeyVault@2
  inputs:
    connectedServiceName: ${{ parameters.connectionName }}
    keyVaultName: ${{ parameters.kevaultName }}
    secretsFilter: ${{ parameters.certificateName }}

- script: |
    TMP_FILE=$(mktemp)
    echo "$CERTIFICATE" | base64 -d > $TMP_FILE
    sudo mkdir -p /etc/certificates
    openssl pkcs12 -in $TMP_FILE -clcerts --nokeys -nodes -passin pass: | sed -z -e "s/.*\(-----BEGIN CERTIFICATE\)/\1/" | sudo tee ${{ parameters.privateKeyPath }} 1>/dev/null
    openssl pkcs12 -in $TMP_FILE -nocerts -nodes -passin pass: | sed -z -e "s/.*\(-----BEGIN PRIVATE KEY\)/\1/" | sudo tee ${{ parameters.certificatePath }} 1>/dev/null
    rm $TMP_FILE
  env:
    CERTIFICATE: $(${{ parameters.certificateName }})
  displayName: "Save certificate"
