# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 8 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
    - '202012'
  always: true

trigger: none
pr: none

stages:
- stage: Build
  variables:
    CACHE_MODE: wcache
    ${{ if eq(variables['Build.SourceBranchName'], '202012') }}:
      VERSION_CONTROL_OPTIONS: 'SONIC_VERSION_CONTROL_COMPONENTS=deb,py2,py3,web'

  jobs:
  - template: azure-pipelines-build.yml
    parameters:
      buildOptions: $[variables.VERSION_CONTROL_OPTIONS] SONIC_BUILD_JOBS=$(nproc)
      jobFilters:
      - vs
      postSteps:
      - script: |
          make freeze
          git status files/build/versions
          git add files/build/versions
          git diff HEAD files/build/versions
        displayName: "Show git diff"