# This workflow will merge pull requests automatically
#

name: automerge
on:
  check_suite:
    types:
      - completed
    branches:
    - 'master'
    - 'xumia/202012'
    paths:
    - 'files/build/versions/**'
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - name: automerge
      if: github.event.pull_request.user.login == 'xumia'
      uses: 'pascalgn/automerge-action@v0.13.1'
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        MERGE_LABELS: ''
        MERGE_METHOD: 'squash'
        MERGE_FILTER_AUTHOR: 'xumia'
        MERGE_DELETE_BRANCH: true
