# This workflow will merge pull requests automatically
#

name: automerge
on:
  pull_request:
    types:
    - opened
    - reopened
    branches:
    - 'master'
    paths:
    - 'files/build/versions/**'
  check_suite:
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - name: automerge
      if: github.event.pull_request.user.login == 'xumia'
      uses: 'pascalgn/automerge-action@v0.13.1'
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        MERGE_LABELS: ''
        MERGE_METHOD: "squash"
