# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily Build
  branches:
    include:
    - xumia/*

pool: sonicbld

stages:
- stage: Build
  variables:
    BUILD_TIMESTAMP: $[format('{0:yyyyMMdd}.{0:HHmmss}', pipeline.startTime)]
    BUILD_NUMBER: $(Build.BuildId)
    OVERRIDE_BUILD_VARS: 'SKIP_INSTALLER_BUILD=y'
  jobs:
  - template: azure-pipelines-build.yml 
- stage: UpgradeVersions
  jobs:
  - job: UpgradeVersions
    steps:
    - script: |
        # Clean up
        [ -d target ] && sudo rm -rf target
        [ -d fsroot ] && sudo rm -rf fsroot
        exit 0
      displayName: 'cleanup'
    - checkout: self
      #submodules: recursive
      displayName: 'Checkout code'
    - download: current
      patterns: '**'
    - script: |
        echo "test"
        ls -l .
        echo "ArtifactsDirectory=$(Pipeline.Workspace)"
      displayName: "Upgrade Versions"
    
