parameters:
- name: 'preSteps'
  type: stepList
  default: []
- name: "postSteps"
  type: stepList
  default: []
- name: 'builds'
  type: object
  default:
  - name: 'none'
    script: ''
    buildSteps: []
- name: 'timeoutInMinutes'
  type: 'number'
  default: 1440
jobs:
- ${{ each build in parameters.builds }}:
  - job: ${{ format('Build_{0}', build.name) }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    variables:
      BUILD_NAME: ${{ build.name }}
    steps:
    - ${{ parameters.preSteps }}
    - ${{ if ne(build.script, '') }}:
      - script: |
          ${{ build.script }}
        displayName: 'BuildScript'
    - ${{ if ne(build.script, '') }}:
      - ${{ parameters.buildSteps }}
    - ${{ parameters.postSteps }}
