parameters:
- name: 'buildOptions'
  type: string
  default: 'SONIC_CONFIG_BUILD_JOBS=4 INSTALL_DEBUG_TOOLS=y'
jobs:
- template: azure-pipelines-comon-build.yml 
  parameters:
    preSteps:
      - script: |
          [ -d target ] && sudo rm -rf target
          [ -d fsroot ] && sudo rm -rf fsroot
        displayName: 'Init'
      - checkout: self
        submodules: recursive
        displayName: 'Checkout code'
      - script: |
          OPTIONS="${{ parameters.buildOptions }} PLATFORM=$BUILD_NAME"
          echo "make $OPTIONS configure"
        displayName: 'Make configure'
    postSteps:
      - publish: $(System.DefaultWorkingDirectory)/target
        artifact: 'sonic-buildimage.$(BUILD_NAME)'
        displayName: "Archive sonic image"
    builds:
      - name: vs
        script: |
          make ${{ parameters.buildOptions }} ENABLE_SYNCD_RPC=y target/sonic-vs.bin
          make ${{ parameters.buildOptions }} target/docker-sonic-vs.gz
      - name: broadcom
        script: |
          make ${{ parameters.buildOptions }} target/sonic-aboot-broadcom.swi
      - name: barefoot
        script: |
          make ${{ parameters.buildOptions }} target/sonic-barefoot.bin target/sonic-aboot-barefoot.swi
      - name: centec
        script: |
          make ${{ parameters.buildOptions }} target/sonic-centec.bin 
          make ${{ parameters.buildOptions }} ENABLE_SYNCD_RPC=y target/docker-syncd-centec-rpc.gz
      - name: innovium
        script: |
          make ${{ parameters.buildOptions }} target/sonic-innovium.bin
      - name: mellanox
        script: |
          make ${{ parameters.buildOptions }} target/sonic-mellanox.bin
          make ${{ parameters.buildOptions }} ENABLE_SYNCD_RPC=y target/docker-syncd-mlnx-rpc.gz target/docker-ptf-mlnx.gz
      - name: innovium
        script: |
          make ${{ parameters.buildOptions }} target/sonic-innovium.bin
      - name: nephos
        script: |
          make ${{ parameters.buildOptions }} target/sonic-nephos.bin
