parameters:
- name: 'buildOptions'
  type: string
  default: ''
jobs:
- template: azure-pipelines-comon-build.yml 
  parameters:
    preSteps:
      - script: |
          # Clean up
          [ -d target ] && sudo rm -rf target
          [ -d fsroot ] && sudo rm -rf fsroot
          # Make configure
          OPTIONS="${{ parameters.buildOptions }} PLATFORM=$BUILD_NAME"
          echo "make $OPTIONS configure"
        displayName: 'Pre Step'
      - checkout: self
        #submodules: recursive
        displayName: 'Checkout code'
      - script: |
          mkdir -p target/versions
          echo "test" > target/result.log
          echo "11" > target/versions/version1.log
          find target
        displayName: 'Fake versions'
    postSteps:
      - publish: $(System.DefaultWorkingDirectory)/target
        artifact: 'sonic-buildimage.$(BUILD_NAME)'
        displayName: "Archive sonic image"
      - script: |
          mkdir -p $(System.DefaultWorkingDirectory)/target/_versions
          mv $(System.DefaultWorkingDirectory)/target/versions $(System.DefaultWorkingDirectory)/target/_versions/versions.$(BUILD_NAME)
        displayName: "Move version files"
      - publish: $(System.DefaultWorkingDirectory)/target/_versions
        artifact: 'sonic-buildimage.versions.$(BUILD_NAME)'
        displayName: "Archive sonic versions"
      - script: |
          echo "PostStep 2"
        displayName: "PostStep 2"
    builds:
      - name: vs
        script: |
          echo "Run script"
        buildSteps:
        - script: |
            echo "BuildStep 1"
          displayName: "BuildStep 1"
        - script: |
            echo "BuildStep 2"
          displayName: "BuildStep 2"
      - name: broadcom
        script: |
          echo "Run script"
        buildSteps:
        - script: |
            echo "BuildStep 1"
          displayName: "BuildStep 1"
        - script: |
            echo "BuildStep 2"
          displayName: "BuildStep 2"
