parameters:
- name: 'buildNames'
  type: object
  default: ''
- name: 'buildOptions'
  type: string
  default: 'SONIC_CONFIG_BUILD_JOBS=1 INSTALL_DEBUG_TOOLS=y'
jobs:
- template: azure-pipelines-comon-build.yml 
  parameters:
    buildNames: ${{ parameters.buildNames }}
    preSteps:
      - script: |
          sudo rm -rf *
        displayName: 'Init'
      - checkout: self
        submodules: recursive
        displayName: 'Checkout code'
      - script: |
          OPTIONS="${{ parameters.buildOptions }} PLATFORM=$BUILD_NAME"
          make $OPTIONS configure
        displayName: 'Make configure'
    postSteps:
      - publish: $(System.DefaultWorkingDirectory)/target
        artifact: 'sonic-buildimage.$(BUILD_NAME)'
        displayName: "Archive sonic image"
    builds:
      - name: vs
        script: |
          make ${{ parameters.buildOptions }} target/sonic-vs.img.gz
      - name: broadcom
        script: |
          make ${{ parameters.buildOptions }} target/sonic-aboot-broadcom.swi
      - name: barefoot
        script: |
          make ${{ parameters.buildOptions }} target/sonic-barefoot.bin target/sonic-aboot-barefoot.swi
      - name: centec
        script: |
          make ${{ parameters.buildOptions }} target/sonic-centec.bin 
          make ${{ parameters.buildOptions }} INSTALL_DEBUG_TOOLS= ENABLE_SYNCD_RPC=y target/docker-syncd-centec-rpc.gz
      - name: innovium
        script: |
          make ${{ parameters.buildOptions }} target/sonic-innovium.bin
      - name: mellanox
        script: |
          make ${{ parameters.buildOptions }} target/sonic-mellanox.bin
          make ${{ parameters.buildOptions }} INSTALL_DEBUG_TOOLS= ENABLE_SYNCD_RPC=y target/docker-syncd-mlnx-rpc.gz
      - name: nephos
        script: |
          make ${{ parameters.buildOptions }} target/sonic-nephos.bin
